// src/assets/index.ts

export { default as CSS } from "@/assets/icons/logo_css3.svg";
export { default as Discord } from "@/assets/icons/logo_discord.svg";
export { default as Django } from "@/assets/icons/logo_django.svg";
export { default as Fastapi } from "@/assets/icons/logo_fastapi.svg";
export { default as Figma } from "@/assets/icons/logo_figma.svg";
export { default as Git } from "@/assets/icons/logo_git.svg";
export { default as Github } from "@/assets/icons/logo_github.svg";
export { default as HTML } from "@/assets/icons/logo_html5.svg";
export { default as Instagram } from "@/assets/icons/logo_instagram.svg";
export { default as LinkedIn } from "@/assets/icons/logo_linkedin.svg";
export { default as MySQL } from "@/assets/icons/logo_mysql.svg";
export { default as NextJs } from "@/assets/icons/logo_nextjs.svg";
export { default as Node } from "@/assets/icons/logo_nodejs.svg";
export { default as Pnpm } from "@/assets/icons/logo_pnpm.svg";
export { default as PostgreSQL } from "@/assets/icons/logo_postgres.svg";
export { default as Python } from "@/assets/icons/logo_python.svg";
export { default as React2 } from "@/assets/icons/logo_react.svg";
export { default as Redux } from "@/assets/icons/logo_redux.svg";
export { default as Rust } from "@/assets/icons/logo_rust.svg";
export { default as SqlAlchemy } from "@/assets/icons/logo_sqlalchemy.svg";
export { default as Sqlite } from "@/assets/icons/logo_sqlite.svg";
export { default as Tailwind } from "@/assets/icons/logo_tailwind.svg";
export { default as TypeScript } from "@/assets/icons/logo_typescript.svg";
export { default as Vercel } from "@/assets/icons/logo_vercel.svg";
export { default as Vite } from "@/assets/icons/logo_vite.svg";
export { default as Vscode } from "@/assets/icons/logo_vscode.svg";
export { default as Zed } from "@/assets/icons/logo_zed.svg";
